kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
stringData:
  cookie: ERLANG_COOKIE
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  url: amqp://{{ .Values.username }}:{{ .Values.password }}@{{ .Values.service.loadbalancer.name }}
type: Opaque
