apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: sunday.appcd.cn
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80
            path: /
